 
/* 
 CREATE TABLE CPT_FACT_ORDERS_AGG AS
 select 
(YEAR FROM fechapedido) as annio
 ,EXTRACT(YEAR FROM fechapedido)*100+ EXTRACT(month FROM fechapedido) AS periodopedido
 ,EXTRACT(week FROM fechapedido) AS semana
 ,fabricante
 ,NOMBREFABRICANTE
 ,TIENDA
 ,NOMBRETIENDA
 ,material
 ,NOMBREMATERIAL
 ,sum(cantidaddepedido) as cantidaddepedido
 ,um
 ,sum(valortotalpedido) as valortotalpeido
 ,UPPER(COMUNA) AS COMUNA
 ,UPPER(BARRIO) AS BARRIO
 ,case 	when UPPER(POBLACION) like 'MEDELL%' then 'MEDELLIN' 
 		when UPPER(POBLACION) like 'JAMUND%' then 'JAMUNDI'
		when UPPER(POBLACION) like 'ITAGU%' then 'ITAGUI' 
		when UPPER(POBLACION) like 'SANTIAGO DE CAL%' then 'CALI'AS
		ELSE UPPER(POBLACION) END AS POBLACION
,upper(categoria)
,upper(subcategoria)
  from fact_orders_categorized
 group by 
(YEAR FROM fechapedido)
 ,EXTRACT(YEAR FROM fechapedido)*100+ EXTRACT(month FROM fechapedido) AS periodopedido
 ,EXTRACT(week FROM fechapedido) AS semana
 ,fabricante
 ,NOMBREFABRICANTE
 ,TIENDA
 ,NOMBRETIENDA
 ,material
 ,NOMBREMATERIAL
 ,um
 ,UPPER(COMUNA)
 ,UPPER(BARRIO)
 ,case 	when UPPER(POBLACION) like 'MEDELL%' then 'MEDELLIN' 
 		when UPPER(POBLACION) like 'JAMUND%' then 'JAMUNDI'
		when UPPER(POBLACION) like 'ITAGU%' then 'ITAGUI' 
		when UPPER(POBLACION) like 'SANTIAGO DE CAL%' then 'CALI'AS
		ELSE UPPER(POBLACION) END
,upper(categoria)
,upper(subcategoria)
 
CREATE INDEX IDX ON CPT_FACT_ORDERS_AGG (fabricante, material, periodopedido, semana, comuna, barrio, poblacion);
*/
----- actualiza la tabla que alimenta la parte de reportería del tablero.
delete from  CPT_FACT_ORDERS_AGG ;

insert into CPT_FACT_ORDERS_AGG 
 select 
EXTRACT(YEAR FROM fechapedido) as annio
 ,EXTRACT(YEAR FROM fechapedido)*100+ EXTRACT(month FROM fechapedido) AS periodopedido
 ,EXTRACT(week FROM fechapedido) AS semana
 ,fabricante
 ,NOMBREFABRICANTE
 ,TIENDA
 ,NOMBRETIENDA
 ,material
 ,NOMBREMATERIAL
 ,sum(cantidaddepedido) as cantidaddepedido
 ,um
 ,sum(valortotalpedido) as valortotalpeido
 ,UPPER(COMUNA) AS COMUNA
 ,UPPER(BARRIO) AS BARRIO
 ,case 	when UPPER(POBLACION) like 'MEDELL%' then 'MEDELLIN' 
 		when UPPER(POBLACION) like 'JAMUND%' then 'JAMUNDI'
		when UPPER(POBLACION) like 'ITAGU%' then 'ITAGUI' 
		when UPPER(POBLACION) like 'SANTIAGO DE CAL%' then 'CALI'
		ELSE UPPER(POBLACION) END AS POBLACION
,upper(categoria)
,upper(subcategoria)
  from fact_orders_categorized
 group by 
EXTRACT(YEAR FROM fechapedido)
 ,EXTRACT(YEAR FROM fechapedido)*100+ EXTRACT(month FROM fechapedido)
 ,EXTRACT(week FROM fechapedido)
 ,fabricante
 ,NOMBREFABRICANTE
 ,TIENDA
 ,NOMBRETIENDA
 ,material
 ,NOMBREMATERIAL
 ,um
 ,UPPER(COMUNA)
 ,UPPER(BARRIO)
 ,case 	when UPPER(POBLACION) like 'MEDELL%' then 'MEDELLIN' 
 		when UPPER(POBLACION) like 'JAMUND%' then 'JAMUNDI'
		when UPPER(POBLACION) like 'ITAGU%' then 'ITAGUI' 
		when UPPER(POBLACION) like 'SANTIAGO DE CAL%' then 'CALI'
		ELSE UPPER(POBLACION) END
,upper(categoria)
,upper(subcategoria)



---------------------hace la transpuesta de la salidad del vec (alistan el power bI) ------------ 


DROP TABLE VEC_OUTPUT_UNPIVOT_TEMP;
CREATE TABLE VEC_OUTPUT_UNPIVOT_TEMP AS (
SELECT t.index AS INDEX_, 1000 AS SEMANA,  CAST('VALIDAR' AS VARCHAR(50)) CATEGORY, CAST('VALIDAR' AS VARCHAR(50)) AS  SUBCATEGORY, CAST('VALIDAR' AS VARCHAR(50)) AS MANUFACTURER, col_name, col_value
FROM vec_output t
CROSS JOIN LATERAL (VALUES('ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.'
						   , t."ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.")
					,('DETERGENTE_PARA_ROPA_otros', "DETERGENTE_PARA_ROPA_otros")
,('MASCOTAS_otros', "MASCOTAS_otros")
,('MEDICAMENTOS_otros', "MEDICAMENTOS_otros")
,('MUNDO_BEBES_otros', "MUNDO_BEBES_otros")
,('MUNDO_BEBE_otros', "MUNDO_BEBE_otros")
,('OTRAS_CATEGORIAS_otros', "OTRAS_CATEGORIAS_otros")
,('Otros', "Otros")
,('SALUD_Y_BIENESTAR_otros', "SALUD_Y_BIENESTAR_otros")
,('_BEBIDAS_otros', "_BEBIDAS_otros")
,('ALIMENTOS_otros', "ALIMENTOS_otros")
,('ASEO_DEL_HOGAR_otros', "ASEO_DEL_HOGAR_otros")
,('ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.', "ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.")
,('ASEO_HOGAR_otros', "ASEO_HOGAR_otros")
,('ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA', "ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA")
,('ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S', "ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S")
,('ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A', "ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A")
,('ASEO_PERSONAL_otros', "ASEO_PERSONAL_otros")
,('BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A', "BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A")
,('BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.', "BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.")
,('BEBIDAS_otros', "BEBIDAS_otros")
,('CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S', "CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S")
,('CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A', "CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A")
,('CONFITERIA_Y_SNACKS_otros', "CONFITERIA_Y_SNACKS_otros")
,('CONFITERIA_otros', "CONFITERIA_otros")
					
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ")
,('ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL', "ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL")
,('ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L', "ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L")
				
) s(col_name, col_value)



UPDATE VEC_OUTPUT_UNPIVOT_TEMP
SET 
CATEGORY = CASE WHEN col_name LIKE 'ALIMENTOS%' THEN 'ALIMENTOS'
				WHEN col_name LIKE 'CONFITERIA%' THEN 'CONFITERIA'
				WHEN col_name LIKE 'BEBIDAS%' THEN 'BEBIDAS'
				WHEN col_name LIKE 'ASEO_PERSONAL%' THEN 'ASEO PERSONAL'
				WHEN col_name LIKE 'ASEO_HOGAR%' THEN 'ASEO HOGAR'
				WHEN col_name LIKE 'MASCOTAS%' THEN 'MASCOTAS'
				WHEN col_name LIKE 'MEDICAMENTOS%' THEN 'MEDICAMENTOS'
				WHEN col_name LIKE 'MUNDO_BEBE%' THEN 'MUNDO BEBES'
				WHEN col_name LIKE 'MUNDO_BEBE%' THEN 'MUNDO BEBES'
				ELSE 'VALIDAR'END 
,SUBCATEGORY = CASE WHEN col_name LIKE '%ACEITES_Y_VINAGRES%' THEN 'ACEITES YVINAGRES'
				WHEN col_name LIKE '%AZUCAR,_PANELA_Y_ENDULZANTES%' THEN 'AZUCAR, PANELA YENDULZANTES'
				WHEN col_name LIKE '%ARROZ,_GRANOS_Y_PASTA%' THEN 'ARROZ, GRANOS Y PASTA'
				WHEN col_name LIKE '%GASEOSAS%' THEN 'GASEOSAS'
				WHEN col_name LIKE '%CAF%' AND col_name LIKE '%MOLIDO%'  THEN 'CAFE MOLIDO'
				WHEN col_name LIKE '%JABON_EN_BARRA%' THEN 'JABON EN BARRA'
				WHEN col_name LIKE '%CREMA_DENTAL%' THEN 'CREMA DENTAL'
				WHEN col_name LIKE '%PAPEL_HIGIENICO%' THEN 'PAPEL HIGIENICO'
				WHEN col_name LIKE '%PASABOCAS%' THEN 'PASABOCAS'
				WHEN col_name LIKE '%CONDIMENTOS%' THEN 'CONDIMENTOS, CALTOS Y SAL'
				WHEN col_name LIKE '%ENLATADOS,_SALSAS%' THEN 'ENLATADOS, SALSAS Y CONSERVAS'
				WHEN col_name LIKE '%_CEREALES_%' THEN 'CEREALES'
				WHEN col_name LIKE '%_otros' THEN 'OTROS'
				ELSE 'VALIDAR' END
				
,MANUFACTURER = CASE WHEN col_name LIKE '%_FLORHUILA%' THEN 'FLORHUILA'
						WHEN col_name LIKE '%_ROA_S.A%' THEN 'ORGANIZACION ROA'
						WHEN col_name LIKE '%_TEAM_FOODS_COLOMBIA%' THEN 'TEAM FOODS COLOMBIA'
						WHEN col_name LIKE '%_REFISAL' THEN 'REFISAL'
						WHEN col_name LIKE '%_COLGATE_PALMOLIVE%' THEN 'COLGATE PALMOLIVE'
						WHEN col_name LIKE '%_DRYPERS_ANDINA%' THEN 'DRYPERS ANDINA'
						WHEN col_name LIKE '%_PROCON_%' THEN 'COMERCIALIZADORA PROCON'
						WHEN col_name LIKE '%INDUSTRIA_NACIONAL_DE_GASEOSAS%' THEN 'INDUSTRIA NACIONAL DE GASEOSAS'
						WHEN col_name LIKE '%EMPAQUETADOS_EL_TRECE%' THEN 'EMPAQUETADOS EL TRECE'
						WHEN col_name LIKE '%PRODUCTOS_YUPI%' THEN 'PRODUCTOS_YUPI'
						WHEN col_name LIKE '%KELLOGG_DE_COLOMBIA_%' THEN 'KELLOGG DE COLOMBIA'
						WHEN col_name LIKE '%AGROINDUSTRIAL_MOLINO_SONORA%' THEN 'AGROINDUSTRIAL MOLINO SONORA'
						WHEN col_name LIKE '%ARROCERA_LA_ESMERALDA%' THEN 'ARROCERA LA ESMERALDA'
						WHEN col_name LIKE '%_otros' THEN 'OTROS'
				ELSE 'VALIDAR' END;
;

SELECT * FROM VEC_OUTPUT_UNPIVOT_TEMP LIMIT 100;
				
			-------------------- hace la transpuesta de vec de entrada ---------------------	
				
CREATE TABLE VEC_INPUT_UNPIVOT_TEMP AS (
SELECT t.DATE AS fECHA_ORDEN, TO_DATE(T.DATE, 'YYYY-MM-DD') AS DATEORDER, EXTRACT(YEAR FROM TO_DATE(T.DATE, 'YYYY-MM-DD') ) AS YEAR_
,EXTRACT(WEEK FROM TO_DATE(T.DATE, 'YYYY-MM-DD') ) AS  WEEK_ ,CAST('VALIDAR' AS VARCHAR(50)) CATEGORY, CAST('VALIDAR' AS VARCHAR(50)) AS MANUFACTURER, col_name, col_value
FROM vec_INPUT t
CROSS JOIN LATERAL (VALUES('ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.'
						   , t."ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.")
					,('DETERGENTE_PARA_ROPA_otros', "DETERGENTE_PARA_ROPA_otros")
,('MASCOTAS_otros', "MASCOTAS_otros")
,('MEDICAMENTOS_otros', "MEDICAMENTOS_otros")
,('MUNDO_BEBES_otros', "MUNDO_BEBES_otros")
,('MUNDO_BEBE_otros', "MUNDO_BEBE_otros")
,('OTRAS_CATEGORIAS_otros', "OTRAS_CATEGORIAS_otros")
,('Otros', "Otros")
,('SALUD_Y_BIENESTAR_otros', "SALUD_Y_BIENESTAR_otros")
,('_BEBIDAS_otros', "_BEBIDAS_otros")
,('ALIMENTOS_otros', "ALIMENTOS_otros")
,('ASEO_DEL_HOGAR_otros', "ASEO_DEL_HOGAR_otros")
,('ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.', "ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.")
,('ASEO_HOGAR_otros', "ASEO_HOGAR_otros")
,('ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA', "ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA")
,('ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S', "ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S")
,('ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A', "ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A")
,('ASEO_PERSONAL_otros', "ASEO_PERSONAL_otros")
,('BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A', "BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A")
,('BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.', "BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.")
,('BEBIDAS_otros', "BEBIDAS_otros")
,('CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S', "CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S")
,('CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A', "CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A")
,('CONFITERIA_Y_SNACKS_otros', "CONFITERIA_Y_SNACKS_otros")
,('CONFITERIA_otros', "CONFITERIA_otros")
					
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ")
,('ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL', "ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL")
,('ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L', "ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L")
				
) s(col_name, col_value)
;




CREATE TABLE VEC_INPUT_UNPIVOT_TEMP AS (
SELECT t.DATE AS fECHA_ORDEN, TO_DATE(T.DATE, 'YYYY-MM-DD') AS DATEORDER, EXTRACT(YEAR FROM TO_DATE(T.DATE, 'YYYY-MM-DD') ) AS YEAR_
,EXTRACT(WEEK FROM TO_DATE(T.DATE, 'YYYY-MM-DD') ) AS  WEEK_ ,CAST('VALIDAR' AS VARCHAR(50)) CATEGORY, CAST('VALIDAR' AS VARCHAR(50)) AS MANUFACTURER, col_name, col_value
FROM vec_INPUT t
CROSS JOIN LATERAL (VALUES('ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.'
						   , t."ALIMENTOS_ACEITES_Y_VINAGRES_TEAM_FOODS_COLOMBIA_S.A.")
					,('DETERGENTE_PARA_ROPA_otros', "DETERGENTE_PARA_ROPA_otros")
,('MASCOTAS_otros', "MASCOTAS_otros")
,('MEDICAMENTOS_otros', "MEDICAMENTOS_otros")
,('MUNDO_BEBES_otros', "MUNDO_BEBES_otros")
,('MUNDO_BEBE_otros', "MUNDO_BEBE_otros")
,('OTRAS_CATEGORIAS_otros', "OTRAS_CATEGORIAS_otros")
,('Otros', "Otros")
,('SALUD_Y_BIENESTAR_otros', "SALUD_Y_BIENESTAR_otros")
,('_BEBIDAS_otros', "_BEBIDAS_otros")
,('ALIMENTOS_otros', "ALIMENTOS_otros")
,('ASEO_DEL_HOGAR_otros', "ASEO_DEL_HOGAR_otros")
,('ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.', "ASEO_HOGAR_JABON_EN_BARRA_DETERGENTES_LTDA.")
,('ASEO_HOGAR_otros', "ASEO_HOGAR_otros")
,('ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA', "ASEO_PERSONAL_CREMA_DENTAL_COLGATE_PALMOLIVE_COMPAIA")
,('ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S', "ASEO_PERSONAL_OTROS_ASEO_PERSONAL_EMPAQUETADOS_EL_TRECE_S.A.S")
,('ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A', "ASEO_PERSONAL_PAPEL_HIGIENICO_DRYPERS_ANDINA_S.A")
,('ASEO_PERSONAL_otros', "ASEO_PERSONAL_otros")
,('BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A', "BEBIDAS_CAF_MOLIDO_COMERCIALIZADORA_PROCON_S.A")
,('BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.', "BEBIDAS_GASEOSAS_INDUSTRIA_NACIONAL_DE_GASEOSAS_S.A.")
,('BEBIDAS_otros', "BEBIDAS_otros")
,('CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S', "CONFITERIA_PASABOCAS_PRODUCTOS_YUPI_S.A.S")
,('CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A', "CONFITERIA_Y_SNACKS_CEREALES_KELLOGG_DE_COLOMBIA_S.A")
,('CONFITERIA_Y_SNACKS_otros', "CONFITERIA_Y_SNACKS_otros")
,('CONFITERIA_otros', "CONFITERIA_otros")
					
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_AGROINDUSTRIAL_MOLINO_SONORA_A.")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROCERA_LA_ESMERALDA_S.A.S")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ARROZ_FLORHUILA_S.A")
,('ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A', "ALIMENTOS_ARROZ,_GRANOS_Y_PASTA_ORGANIZACION_ROA_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_EMPAQUETADOS_EL_TRECE_S.")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_MAYAG_EZ_S.A")
,('ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ', "ALIMENTOS_AZUCAR,_PANELA_Y_ENDULZANTES_PRODUCTORA_Y_COMERCIALIZ")
,('ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL', "ALIMENTOS_CONDIMENTOS,_CALDOS_Y_SAL_REFISAL")
,('ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L', "ALIMENTOS_ENLATADOS,_SALSAS_Y_CONSERVAS_COMPAIA_NACIONAL_DE_L")
				
) s(col_name, col_value)